version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Admin@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
      - "8090:8080"
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      SQLConnection: "Server=localhost;Database=db;User Id=sa;Password=Admin@123;Trusted_Connection=False;TrustServerCertificate=True; MultipleActiveResultSets=true"